// web/frontend/src/components/navigation.vue
<script setup lang="ts">

import { ref, onMounted, onUnmounted } from 'vue';
import { grpc } from '@improbable-eng/grpc-web';
import { toast } from '../lib/toast';
import { filterResources } from '../lib/resource';
import { Client, commonApi, robotApi, navigationApi, type ServiceError, ResponseStream } from '@viamrobotics/sdk';
import { Struct } from 'google-protobuf/google/protobuf/struct_pb';
import { rcLogConditionally } from '../lib/log';

const props = defineProps<{
  resources: commonApi.ResourceName.AsObject[]
  name:string
  client: Client
  statusStream: ResponseStream<robotApi.StreamStatusResponse> | null
}>();

let googleMapsInitResolve: () => void;
const mapReady = new Promise<void>((resolve) => {
  googleMapsInitResolve = resolve;
});

let map: google.maps.Map;
let updateWaypointsId: number;
let updateLocationsId: number;

const mapInit = ref(false);
const googleApiKey = ref('');
const location = ref('');
const res = ref();
const container = ref<HTMLElement>();

const grpcCallback = (
  error: ServiceError | null,
  responseMessage: (navigationApi.SetModeResponse | null),
  stringify = true
) => {
  if (error) {
    toast.error(error.message);
    return;
  }
  if (stringify) {
    try {
      if (responseMessage === null) {
        res.value = null;
        return;
      }

      res.value = JSON.stringify(responseMessage.toObject());
    } catch (_error) {
      toast.error(`${_error}`);
    }
  }
};

const setNavigationMode = (mode: 'manual' | 'waypoint') => {
  let pbMode: 0 | 1 | 2 = navigationApi.Mode.MODE_UNSPECIFIED;

  if (mode === 'manual') {
    pbMode = navigationApi.Mode.MODE_MANUAL;
  } else if (mode === 'waypoint') {
    pbMode = navigationApi.Mode.MODE_WAYPOINT;
  }

  const req = new navigationApi.SetModeRequest();
  req.setName(props.name);
  req.setMode(pbMode);

  rcLogConditionally(req);
  props.client.navigationService.setMode(req, new grpc.Metadata(), grpcCallback);
};

const setNavigationLocation = () => {
  const [latStr, lngStr] = location.value.split(',');
  if (latStr === undefined || lngStr === undefined) {
    return;
  }

  const lat = Number.parseFloat(latStr);
  const lng = Number.parseFloat(lngStr);

  // TODO: Not sure how this works (if it does), robotApi has no ResourceRunCommandRequest method
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const req = new (robotApi as any).ResourceRunCommandRequest();
  let gpsName = '';

  const [gps] = filterResources(props.resources ?? [], 'rdk', 'component', 'gps');

  if (gps) {
    gpsName = gps.name;
  } else {
    toast.error('no gps device found');
    return;
  }

  req.setName(props.name);
  req.setResourceName(gpsName);
  req.setCommandName('set_location');
  req.setArgs(
    Struct.fromJavaScript({
      latitude: lat,
      longitude: lng,
    })
  );

  rcLogConditionally(req);
  props.client.genericService.doCommand(req, new grpc.Metadata(), grpcCallback);
};

const initNavigation = async () => {
  await mapReady;

  map = new window.google.maps.Map(container.value!, { zoom: 18 });
  map.addListener('click', (event: google.maps.MapMouseEvent) => {
    const lat = event.latLng?.lat();
    const lng = event.latLng?.lng();

    if (lat === undefined || lng === undefined) {
      return;
    }

    const req = new navigationApi.AddWaypointRequest();
    const point = new commonApi.GeoPoint();

    point.setLatitude(lat);
    point.setLongitude(lng);
    req.setName(props.name);
    req.setLocation(point);

    rcLogConditionally(req);
    props.client.navigationService.addWaypoint(req, new grpc.Metadata(), grpcCallback);
  });

  let centered = false;
  const knownWaypoints: Record<string, google.maps.Marker> = {};
  let localLabelCounter = 0;

  const updateWaypoints = () => {
    const req = new navigationApi.GetWaypointsRequest();
    req.setName(props.name);

    rcLogConditionally(req);
    props.client.navigationService.getWaypoints(
      req,
      new grpc.Metadata(),
      (err: ServiceError | null, resp: navigationApi.GetWaypointsResponse | null) => {
        grpcCallback(err, resp, false);

        if (err) {
          updateWaypointsId = window.setTimeout(updateWaypoints, 1000);
          return;
        }

        let waypoints: navigationApi.Waypoint[] = [];

        if (resp) {
          waypoints = resp.getWaypointsList();
        }

        const currentWaypoints: Record<string, google.maps.Marker> = {};

        for (const waypoint of waypoints) {
          const pos = {
            lat: waypoint.getLocation()?.getLatitude() ?? 0,
            lng: waypoint.getLocation()?.getLongitude() ?? 0,
          };

          const posStr = JSON.stringify(pos);

          if (knownWaypoints[posStr]) {
            currentWaypoints[posStr] = knownWaypoints[posStr]!;
            continue;
          }

          localLabelCounter += 1;

          const marker = new window.google.maps.Marker({
            position: pos,
            map,
            label: `${localLabelCounter}`,
          });

          currentWaypoints[posStr] = marker;
          knownWaypoints[posStr] = marker;

          marker.addListener('click', () => {
            console.debug('clicked on marker', pos);
          });

          marker.addListener('dblclick', () => {
            const waypointRequest = new navigationApi.RemoveWaypointRequest();
            waypointRequest.setName(props.name);
            waypointRequest.setId(waypoint.getId());

            rcLogConditionally(req);
            props.client.navigationService.removeWaypoint(
              waypointRequest,
              new grpc.Metadata(),
              grpcCallback
            );
          });
        }

        const waypointsToDelete = Object.keys(knownWaypoints).filter(
          (elem) => !(elem in currentWaypoints)
        );

        for (const key of waypointsToDelete) {
          const marker = knownWaypoints[key]!;
          marker.setMap(null);
          delete knownWaypoints[key];
        }

        updateWaypointsId = window.setTimeout(updateWaypoints, 1000);
      }
    );
  };

  updateWaypoints();

  const locationMarker = new window.google.maps.Marker({ label: 'robot' });

  const updateLocation = () => {
    const req = new navigationApi.GetLocationRequest();
    req.setName(props.name);

    rcLogConditionally(req);
    props.client.navigationService.getLocation(
      req,
      new grpc.Metadata(),
      (err: ServiceError | null, resp: navigationApi.GetLocationResponse | null) => {
        grpcCallback(err, resp, false);

        if (err) {
          updateLocationsId = window.setTimeout(updateLocation, 1000);
          return;
        }

        const pos = {
          lat: resp?.getLocation()?.getLatitude() ?? 0,
          lng: resp?.getLocation()?.getLongitude() ?? 0,
        };

        if (!centered) {
          centered = true;
          map.setCenter(pos);
        }

        locationMarker.setPosition(pos);
        locationMarker.setMap(map);

        updateLocationsId = window.setTimeout(updateLocation, 1000);
      }
    );
  };

  updateLocation();
};

const loadMaps = () => {
  if (document.querySelector('#google-maps')) {
    initNavigation();
    return;
  }

  const key = googleApiKey.value;
  const script = document.createElement('script');
  script.id = 'google-maps';
  script.src = `https://maps.googleapis.com/maps/api/js?key=${key}` + 
    `&callback=googleMapsInit&libraries=&v=weekly&map_ids=google-maps-1`;
  script.async = true;
  document.head.append(script);
};

window.googleMapsInit = () => {
  console.debug('google maps is ready');
  googleMapsInitResolve();
};

const initNavigationView = () => {
  window.localStorage.setItem('nav-svc-google-api-key', googleApiKey.value);
  mapInit.value = true;
  loadMaps();
  initNavigation();
};

onMounted(() => {
  const apiKey = window.localStorage.getItem('nav-svc-google-api-key');
  if (apiKey) {
    googleApiKey.value = apiKey;
    initNavigationView();
  }

  props.statusStream?.on('end', () => {
    clearTimeout(updateWaypointsId);
    clearTimeout(updateLocationsId);
  });
});

onUnmounted(() => {
  clearTimeout(updateWaypointsId);
  clearTimeout(updateLocationsId);
});

</script>

<template>
  <v-collapse
    :title="props.name"
    class="navigation"
  >
    <v-breadcrumbs
      slot="title"
      crumbs="navigation"
    />
    <div class="border-border-1 flex flex-col gap-2 border border-t-0 p-4">
      <div class="flex h-full w-full flex-row items-end gap-2">
        <v-input
          label="Google Maps API Key"
          :value="googleApiKey"
          @input="googleApiKey = $event.detail.value"
        />
        <div class="flex h-[30px]">
          <v-button
            label="Go"
            @click="initNavigationView"
          />
        </div>
      </div>
      <div v-show="mapInit">
        <v-radio
          label="Navigation mode"
          options="Manual, Waypoint"
          @input="setNavigationMode($event.detail.value.toLowerCase())"
        />

        <div>
          <v-button
            label="Try Set Location"
            @click="setNavigationLocation()"
          />
        </div>

        <div
          id="google-maps-1"
          ref="container"
          class="mb-2 h-[400px] w-full"
        />

        <v-input
          label="Location"
          :value="location"
          @input="location = $event.detail.value"
        />
      </div>
    </div>
  </v-collapse>
</template>

// web/frontend/src/components/navigation/index.svelte
<svelte:options immutable />

<script setup lang="ts">

import 'maplibre-gl/dist/maplibre-gl.css';
import { grpc } from '@improbable-eng/grpc-web';
import { toast } from '@/lib/toast';
import { filterResources } from '@/lib/resource';
import { Client, commonApi, robotApi, navigationApi, type ServiceError, type ResponseStream } from '@viamrobotics/sdk';
import { Struct } from 'google-protobuf/google/protobuf/struct_pb';
import { rcLogConditionally } from '@/lib/log';
import Collapse from '../collapse.svelte';
import maplibregl from 'maplibre-gl'; 
import { onMount, afterUpdate } from 'svelte';
    import { setMode } from '@/api/navigation';

onMount(() => console.log('mount'))
afterUpdate(() => console.log('update'))

export let resources: commonApi.ResourceName.AsObject[]
export let name: string
export let client: Client
export let statusStream: ResponseStream<robotApi.StreamStatusResponse> | null

let updateWaypointsId: number;
let updateLocationsId: number;

let location = '';

const grpcCallback = (error: ServiceError | null) => {
  if (error) {
    toast.error(error.message);
  }
};

const setNavigationMode = async (event: CustomEvent) => {
  const mode = event.detail.value.toLowerCase() as 'manual' | 'waypoint'

  let pbMode: 0 | 1 | 2 = navigationApi.Mode.MODE_UNSPECIFIED;

  if (mode === 'manual') {
    pbMode = navigationApi.Mode.MODE_MANUAL;
  } else if (mode === 'waypoint') {
    pbMode = navigationApi.Mode.MODE_WAYPOINT;
  }

  setMode(client, name, mode)

  const req = new navigationApi.SetModeRequest();
  req.setName(name);
  req.setMode(pbMode);

  rcLogConditionally(req);
  client.navigationService.setMode(req, new grpc.Metadata(), grpcCallback);
};

const setNavigationLocation = () => {
  const [latStr, lngStr] = location.split(',');
  if (latStr === undefined || lngStr === undefined) {
    return;
  }

  const lat = Number.parseFloat(latStr);
  const lng = Number.parseFloat(lngStr);

  // TODO: Not sure how this works (if it does), robotApi has no ResourceRunCommandRequest method
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const req = new (robotApi as any).ResourceRunCommandRequest();
  let gpsName = '';

  const [gps] = filterResources(resources ?? [], 'rdk', 'component', 'gps');

  if (gps) {
    gpsName = gps.name;
  } else {
    toast.error('no gps device found');
    return;
  }

  req.setName(name);
  req.setResourceName(gpsName);
  req.setCommandName('set_location');
  req.setArgs(
    Struct.fromJavaScript({
      latitude: lat,
      longitude: lng,
    })
  );

  rcLogConditionally(req);
  client.genericService.doCommand(req, new grpc.Metadata(), grpcCallback);
};

let map: maplibregl.Map

const marker = new maplibregl.Marker()

const handleClick = (event: maplibregl.MapMouseEvent) => {
  marker.setLngLat(event.lngLat).addTo(map);

  const { lat, lng } = event.lngLat;

  const req = new navigationApi.AddWaypointRequest();
  const point = new commonApi.GeoPoint();

  point.setLatitude(lat);
  point.setLongitude(lng);
  req.setName(name);
  req.setLocation(point);

  rcLogConditionally(req);
  client.navigationService.addWaypoint(req, new grpc.Metadata(), grpcCallback);
}

const initNavigation = async () => {
  const style = {
    version: 8,
    sources: {
      osm: {
        type: "raster",
        tiles: ["https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"],
        tileSize: 256,
        attribution: "&copy; OpenStreetMap Contributors",
        maxzoom: 19,
      },
    },
    layers: [
      {
        id: "osm",
        type: "raster",
        source: "osm",
      },
    ],
  };

  map = new maplibregl.Map({
    container: 'navigation-map',
    style, // stylesheet location
    center: [-74.5, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
  });

  map.addControl(new maplibregl.NavigationControl());

  map.on('load', () => {
    map.addSource('navigation-map', {
    type: 'geojson',
    data: 'https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_10m_ports.geojson'
  });
  })

  map.on('click', handleClick);

  let centered = false;

  const knownWaypoints: Record<string, maplibregl.Marker> = {};
  let localLabelCounter = 0;

  const updateWaypoints = () => {
    const req = new navigationApi.GetWaypointsRequest();
    req.setName(name);

    rcLogConditionally(req);
    client.navigationService.getWaypoints(
      req,
      new grpc.Metadata(),
      (err: ServiceError | null, resp: navigationApi.GetWaypointsResponse | null) => {
        grpcCallback(err);

        if (err) {
          updateWaypointsId = window.setTimeout(updateWaypoints, 1000);
          return;
        }

        let waypoints: navigationApi.Waypoint[] = [];

        if (resp) {
          waypoints = resp.getWaypointsList();
        }

        const currentWaypoints: Record<string, maplibregl.Marker> = {};

        for (const waypoint of waypoints) {
          const position = {
            lat: waypoint.getLocation()?.getLatitude() ?? 0,
            lng: waypoint.getLocation()?.getLongitude() ?? 0,
          };

          const posStr = JSON.stringify(position);

          if (knownWaypoints[posStr]) {
            currentWaypoints[posStr] = knownWaypoints[posStr]!;
            continue;
          }

          localLabelCounter += 1;

          const marker = new maplibregl.Marker({
            // label: `${localLabelCounter}`,
          });

          marker.setLngLat([position.lng, position.lat]).addTo(map)

          currentWaypoints[posStr] = marker;
          knownWaypoints[posStr] = marker;

          marker.on('dblclick', () => {
            const waypointRequest = new navigationApi.RemoveWaypointRequest();
            waypointRequest.setName(name);
            waypointRequest.setId(waypoint.getId());

            rcLogConditionally(req);
            client.navigationService.removeWaypoint(
              waypointRequest,
              new grpc.Metadata(),
              grpcCallback
            );
          });
        }

        const waypointsToDelete = Object.keys(knownWaypoints).filter(
          (elem) => !(elem in currentWaypoints)
        );

        for (const key of waypointsToDelete) {
          const marker = knownWaypoints[key]!;
          marker.remove();
          delete knownWaypoints[key];
        }

        updateWaypointsId = window.setTimeout(updateWaypoints, 1000);
      }
    );
  };

  updateWaypoints();

  const locationMarker = new maplibregl.Marker({
    // label: 'robot'
  });

  const updateLocation = () => {
    const req = new navigationApi.GetLocationRequest();
    req.setName(name);

    rcLogConditionally(req);
    client.navigationService.getLocation(
      req,
      new grpc.Metadata(),
      (err: ServiceError | null, resp: navigationApi.GetLocationResponse | null) => {
        grpcCallback(err);

        if (err) {
          updateLocationsId = window.setTimeout(updateLocation, 1000);
          return;
        }

        const position = {
          lat: resp?.getLocation()?.getLatitude() ?? 0,
          lng: resp?.getLocation()?.getLongitude() ?? 0,
        };

        if (!centered) {
          centered = true;
          map.setCenter(position);
        }

        locationMarker.setLngLat([position.lng, position.lat]).addTo(map);

        updateLocationsId = window.setTimeout(updateLocation, 1000);
      }
    );
  };

  updateLocation();
};

const handleLocationInput = (event: CustomEvent) => {
  location = event.detail.value
}

const handleToggle = (event: CustomEvent<{ open: boolean }>) => {
  console.log(event)
  const { open } = event.detail

  if (open) {
    handleOpen()
  } else {
    handleClose()
  }
}

const handleOpen = () => {
  initNavigation();

  statusStream?.on('end', () => {
    clearTimeout(updateWaypointsId);
    clearTimeout(updateLocationsId);
  });
};

const handleClose = () => {
  clearTimeout(updateWaypointsId);
  clearTimeout(updateLocationsId);
};

</script>

<Collapse
  title={name}
  on:toggle={handleToggle}
>
  <v-breadcrumbs
    slot="title"
    crumbs="navigation"
  />

  <div class="flex flex-col gap-2 border border-t-0 border-medium p-4">
    <v-radio
      label="Navigation mode"
      options="Manual, Waypoint"
      on:input={setNavigationMode}
    />

    <v-button
      label="Try Set Location"
      on:click={setNavigationLocation}
    />

    <div
      id='navigation-map'
      class="mb-2 h-[400px] w-full"
    />

    <v-input
      label="Location"
      value={location}
      on:input={handleLocationInput}
    />
  </div>
</Collapse>
