// web/frontend/src/components/keyboard-input.vue
<!-- eslint-disable id-length -->
<script setup lang="ts">

export type Keys = 'w' | 'a' | 's' | 'd'

import { mdiArrowUp as w, mdiRestore as a, mdiReload as d, mdiArrowDown as s } from '@mdi/js';
import Icon from './icon.vue';
import { watch, onUnmounted } from 'vue';

interface Emits {
  (event: 'keydown', key: Keys): void
  (event: 'keyup', key: Keys): void
  (event: 'toggle', active: boolean): void
  (event: 'update-keyboard-state', value: boolean): void
}

const emit = defineEmits<Emits>();

interface Props {
  isActive: boolean,
  tempDisable: boolean,
}

const props = defineProps<Props>();

const keyIcons = { w, a, s, d };

const pressedKeys = $ref({
  w: false,
  a: false,
  s: false,
  d: false,
});

const keysLayout = [['a'], ['w', 's'], ['d']] as const;

const normalizeKey = (key: string): Keys | null => {
  return ({
    w: 'w',
    a: 'a',
    s: 's',
    d: 'd',
    arrowup: 'w',
    arrowleft: 'a',
    arrowdown: 's',
    arrowright: 'd',
  } as Record<string, Keys>)[key.toLowerCase()] ?? null;
};

const emitKeyDown = (key: Keys) => {
  if (props.tempDisable) {
    return;
  }
  
  pressedKeys[key] = true;

  emit('keydown', key);
};

const emitKeyUp = (key: Keys) => {
  pressedKeys[key] = false;
  emit('keyup', key);
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (props.tempDisable) {
    return;
  }

  event.preventDefault();
  event.stopPropagation();

  const key = normalizeKey(event.key);

  if (key === null || pressedKeys[key]) {
    return;
  }

  emitKeyDown(key);
};

const handleKeyUp = (event: KeyboardEvent) => {
  if (props.tempDisable) {
    return;
  }

  event.preventDefault();
  event.stopPropagation();

  const key = normalizeKey(event.key);
  if (key !== null) {
    emitKeyUp(key);
  }
};

const toggleKeyboard = (nowActive: boolean) => {
  if (nowActive) {
    window.addEventListener('keydown', handleKeyDown, false);
    window.addEventListener('keyup', handleKeyUp, false);
  } else {
    window.removeEventListener('keydown', handleKeyDown);
    window.removeEventListener('keyup', handleKeyUp);
  }

  emit('update-keyboard-state', nowActive);
  emit('toggle', nowActive);
};

const handlePointerDown = (key: Keys) => {
  emitKeyDown(key);
};

const handlePointerUp = (key: Keys) => {
  emitKeyUp(key);
};

watch(() => props.isActive, (active) => {
  if (!active) {
    toggleKeyboard(false);
  }
});

onUnmounted(() => {
  toggleKeyboard(false);
});

</script>

<template>
  <div>
    <v-switch
      :label="props.isActive ? 'Keyboard Enabled' : 'Keyboard Disabled'"
      class="pr-4 w-fit"
      :value="props.isActive ? 'on' : 'off'"
      @input="toggleKeyboard($event.detail.value)"
    />
    <div class="flex gap-2">
      <div
        v-for="(lineKeys, index) in keysLayout"
        :key="index"
        class="my-1 flex flex-col self-end gap-2"
      >
        <button
          v-for="key in lineKeys"
          :key="key"
          class="flex items-center gap-1.5 border border-gray-500 px-3 py-1 outline-none uppercase"
          :class="{
            'bg-gray-200 text-gray-800': pressedKeys[key],
            'bg-white': !pressedKeys[key],
          }"
          @pointerdown="handlePointerDown(key)"
          @pointerup="handlePointerUp(key)"
          @pointerleave="handlePointerUp(key)"
        >
          {{ key }}
          <Icon :path="keyIcons[key]" />
        </button>
      </div>
    </div>
  </div>
</template>

// web/frontend/src/components/keyboard-input/index.svelte
<script lang="ts">
  /* eslint-disable id-length */
  import { onDestroy } from 'svelte';

  export type Keys = 'w' | 'a' | 's' | 'd';

  import {
    mdiArrowUp as w,
    mdiRestore as a,
    mdiReload as d,
    mdiArrowDown as s,
  } from '@mdi/js';
  import Icon from '../icon/index.svelte';

  export let isActive: boolean;
  export let onKeyDown: (key: Keys) => void;
  export let onKeyUp: (key: Keys) => void;
  export let onUpdateKeyboardState: (isActive: boolean) => void;

  const keyIcons = { w, a, s, d };

  const pressedKeys = {
    w: false,
    a: false,
    s: false,
    d: false,
  };

  const keysLayout = [['a'], ['w', 's'], ['d']] as const;

  const normalizeKey = (key: string): Keys | null => {
    return (
      (
        {
          w: 'w',
          a: 'a',
          s: 's',
          d: 'd',
          arrowup: 'w',
          arrowleft: 'a',
          arrowdown: 's',
          arrowright: 'd',
        } as Record<string, Keys>
      )[key.toLowerCase()] ?? null
    );
  };

  const dispatchKeyDown = (key: Keys) => {
    pressedKeys[key] = true;
    onKeyDown(key);
  };

  const dispatchKeyUp = (key: Keys) => {
    pressedKeys[key] = false;
    onKeyUp(key);
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();

    const key = normalizeKey(event.key);

    if (key === null || pressedKeys[key]) {
      return;
    }

    dispatchKeyDown(key);
  };

  const handleKeyUp = (event: KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();

    const key = normalizeKey(event.key);
    if (key !== null) {
      dispatchKeyUp(key);
    }
  };

  const toggleKeyboard = (nowActive: boolean) => {
    if (nowActive) {
      window.addEventListener('keydown', handleKeyDown, false);
      window.addEventListener('keyup', handleKeyUp, false);
    } else {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    }

    onUpdateKeyboardState(nowActive);
  };

  const handlePointerDown = (key: Keys) => {
    dispatchKeyDown(key);
  };

  const handlePointerUp = (key: Keys) => {
    dispatchKeyUp(key);
  };

  $: if (!isActive) {
    toggleKeyboard(false);
  }

  onDestroy(() => {
    toggleKeyboard(false);
  });
</script>

<div>
  <v-switch
    label={isActive ? 'Keyboard enabled' : 'Keyboard disabled'}
    class="w-fit pr-4"
    value={isActive ? 'on' : 'off'}
    on:input={() => {
      toggleKeyboard(!isActive);
    }}
  />
  <div class="flex justify-center gap-2">
    {#each keysLayout as lineKeys, index (index)}
      <div class="my-1 flex flex-col gap-2 self-end">
        {#each lineKeys as key (key)}
          <button
            class="flex select-none items-center gap-1.5 border border-gray-500 px-3 py-1 uppercase outline-none"
            class:bg-gray-200={pressedKeys[key]}
            class:text-gray-800={pressedKeys[key]}
            class:bg-white={!pressedKeys[key]}
            on:pointerdown={() => {
              handlePointerDown(key);
            }}
            on:pointerup={() => {
              handlePointerUp(key);
            }}
            on:pointerleave={() => {
              handlePointerUp(key);
            }}
          >
            {key}
            <Icon path={keyIcons[key]} />
          </button>
        {/each}
      </div>
    {/each}
  </div>
</div>
