// web/frontend/src/components/board.vue
<script setup lang="ts">

import { toast } from '../lib/toast';
import { displayError } from '../lib/error';
import { rcLogConditionally } from '../lib/log';
import { Client, BoardClient, ServiceError } from '@viamrobotics/sdk';

const props = defineProps<{
  name: string
  status: {
    analogsMap: Record<string, { value: number }>
    digitalInterruptsMap: Record<string, { value: number }>
  }
  client: Client;
}>();

const boardClient = new BoardClient(props.client, props.name, { requestLogger: rcLogConditionally });
const getPin = $ref('');
const setPin = $ref('');
const setLevel = $ref('');
const pwm = $ref('');
const pwmFrequency = $ref('');

let getPinMessage = $ref('');

const getGPIO = async () => {
  try {
    const isHigh = await boardClient.getGPIO(getPin);
    getPinMessage = `Pin: ${getPin} is ${isHigh ? 'high' : 'low'}`;
  } catch (error) {
    toast.error((error as ServiceError).message);
  }
};

const setGPIO = async () => {

  try {
    await boardClient.setGPIO(setPin, setLevel === 'high');
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const getPWM = async () => {
  try {
    const dutyCyclePct = await boardClient.getPWM(getPin);
    getPinMessage = `Pin ${getPin}'s duty cycle is ${dutyCyclePct * 100}%.`;
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const setPWM = async () => {
  try {
    await boardClient.setPWM(setPin, Number.parseFloat(pwm) / 100);
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const getPWMFrequency = async () => {
  try {
    const frequencyHz = await boardClient.getPWMFrequency(getPin);
    getPinMessage = `Pin ${getPin}'s frequency is ${frequencyHz}Hz.`;
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const setPWMFrequency = async () => {
  try {
    await boardClient.setPWMFrequency(setPin, Number.parseFloat(pwmFrequency));
  } catch (error) {
    displayError(error as ServiceError);
  }
};

</script>

<template>
  <v-collapse
    :title="name"
    class="board"
  >
    <v-breadcrumbs
      slot="title"
      crumbs="board"
    />
    <div class="border-medium overflow-auto border border-t-0 p-4">
      <h3 class="mb-2">
        Analogs
      </h3>
      <table class="border-medium mb-4 table-auto border">
        <tr
          v-for="(analog, analogName) in status.analogsMap"
          :key="analogName"
        >
          <th class="border-medium border p-2">
            {{ analogName }}
          </th>
          <td class="border-medium border p-2">
            {{ analog.value || 0 }}
          </td>
        </tr>
      </table>
      <h3 class="mb-2">
        Digital Interrupts
      </h3>
      <table class="border-medium mb-4 w-full table-auto border">
        <tr
          v-for="(di, interruptName) in status.digitalInterruptsMap"
          :key="interruptName"
        >
          <th class="border-medium border p-2">
            {{ interruptName }}
          </th>
          <td class="border-medium border p-2">
            {{ di.value || 0 }}
          </td>
        </tr>
      </table>
      <h3 class="mb-2">
        GPIO
      </h3>
      <table class="border-medium mb-4 w-full table-auto border">
        <tr>
          <th class="border-medium border p-2">
            Get
          </th>
          <td class="border-medium border p-2">
            <div class="flex flex-wrap items-end gap-2">
              <v-input
                label="Pin"
                type="integer"
                :value="getPin"
                @input="getPin = $event.detail.value"
              />
              <v-button
                label="Get Pin State"
                @click="getGPIO"
              />
              <v-button
                label="Get PWM Duty Cycle"
                @click="getPWM"
              />
              <v-button
                label="Get PWM Frequency"
                @click="getPWMFrequency"
              />
              <span class="py-2">
                {{ getPinMessage }}
              </span>
            </div>
          </td>
        </tr>
        <tr>
          <th class="border-medium border p-2">
            Set
          </th>
          <td class="p-2">
            <div class="flex flex-wrap items-end gap-2">
              <v-input
                v-model="setPin"
                type="integer"
                class="mr-2"
                label="Pin"
              />
              <select
                v-model="setLevel"
                class="border-medium mr-2 h-[30px] border bg-white text-sm"
              >
                <option>low</option>
                <option>high</option>
              </select>
              <v-button
                class="mr-2"
                label="Set Pin State"
                @click="setGPIO"
              />
              <v-input
                v-model="pwm"
                label="PWM Duty Cycle"
                type="number"
                class="mr-2"
              />
              <v-button
                class="mr-2"
                label="Set PWM Duty Cycle"
                @click="setPWM"
              />
              <v-input
                v-model="pwmFrequency"
                label="PWM Frequency"
                type="number"
                class="mr-2"
              />
              <v-button
                class="mr-2"
                label="Set PWM Frequency"
                @click="setPWMFrequency"
              />
            </div>
          </td>
        </tr>
      </table>
    </div>
  </v-collapse>
</template>

// web/frontend/src/components/board/index.svelte
<script lang="ts">

import { toast } from '@/lib/toast';
import { displayError } from '@/lib/error';
import { rcLogConditionally } from '@/lib/log';
import { Client, BoardClient, type ServiceError } from '@viamrobotics/sdk';
import Collapse from '@/components/collapse.svelte';

export let name: string;
export let status: {
  analogsMap: Record<string, { value: number }>
  digitalInterruptsMap: Record<string, { value: number }>
};
export let client: Client;

const boardClient = new BoardClient(client, name, { requestLogger: rcLogConditionally });

let getPin = '';
let setPin = '';
let setLevel = '';
let pwm = '';
let pwmFrequency = '';
let getPinMessage = '';

const getGPIO = async () => {
  try {
    const isHigh = await boardClient.getGPIO(getPin);
    getPinMessage = `Pin: ${getPin} is ${isHigh ? 'high' : 'low'}`;
  } catch (error) {
    toast.error((error as ServiceError).message);
  }
};

const setGPIO = async () => {
  try {
    await boardClient.setGPIO(setPin, setLevel === 'high');
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const getPWM = async () => {
  try {
    const dutyCyclePct = await boardClient.getPWM(getPin);
    getPinMessage = `Pin ${getPin}'s duty cycle is ${dutyCyclePct * 100}%.`;
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const setPWM = async () => {
  try {
    await boardClient.setPWM(setPin, Number.parseFloat(pwm) / 100);
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const getPWMFrequency = async () => {
  try {
    const frequencyHz = await boardClient.getPWMFrequency(getPin);
    getPinMessage = `Pin ${getPin}'s frequency is ${frequencyHz}Hz.`;
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const setPWMFrequency = async () => {
  try {
    await boardClient.setPWMFrequency(setPin, Number.parseFloat(pwmFrequency));
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const handleGetPinInput = (event: CustomEvent) => {
  getPin = event.detail.value;
};

const handleSetPinInput = (event: CustomEvent) => {
  setPin = event.detail.value;
}

const handlePwmInput = (event: CustomEvent) => {
  pwm = event.detail.value;
};

const handlePwmFrequencyInput = (event: CustomEvent) => {
  pwmFrequency = event.detail.value;
};

</script>

<Collapse title={name}>
  <v-breadcrumbs
    slot="title"
    crumbs="board"
  />
  <div class="overflow-auto border border-t-0 border-medium p-4">
    <h3 class="mb-2">
      Analogs
    </h3>
    <table class="mb-4 table-auto border border-medium">
      {#each Object.entries(status.analogsMap) as [analogName, analog] (analogName)}
        <tr>
          <th class="border border-medium p-2">
            {analogName}
          </th>
          <td class="border border-medium p-2">
            {analog.value || 0}
          </td>
        </tr>
      {/each}
    </table>

    <h3 class="mb-2">
      Digital Interrupts
    </h3>
    <table class="mb-4 w-full table-auto border border-medium">
      {#each Object.entries(status.digitalInterruptsMap) as [interruptName, interrupt] (interruptName)}
        <tr>
          <th class="border border-medium p-2">
            {interruptName}
          </th>
          <td class="border border-medium p-2">
            {interrupt.value || 0}
          </td>
        </tr>
      {/each}
    </table>

    <h3 class="mb-2">
      GPIO
    </h3>
    <table class="mb-4 w-full table-auto border border-medium">
      <tr>
        <th class="border border-medium p-2">
          Get
        </th>
        <td class="border border-medium p-2">
          <div class="flex flex-wrap items-end gap-2">
            <v-input
              label="Pin"
              type="integer"
              value={getPin}
              on:input={handleGetPinInput}
            />
            <v-button
              label="Get Pin State"
              on:click={getGPIO}
            />
            <v-button
              label="Get PWM Duty Cycle"
              on:click={getPWM}
            />
            <v-button
              label="Get PWM Frequency"
              on:click={getPWMFrequency}
            />
            <span class="py-2">
              {getPinMessage}
            </span>
          </div>
        </td>
      </tr>

      <tr>
        <th class="border border-medium p-2">
          Set
        </th>
        <td class="p-2">
          <div class="flex flex-wrap items-end gap-2">
            <v-input
              value={setPin}
              type="integer"
              class="mr-2"
              label="Pin"
              on:input={handleSetPinInput}
            />
            <select
              bind:value={setLevel}
              class="mr-2 h-[30px] border border-medium bg-white text-sm"
            >
              <option>low</option>
              <option>high</option>
            </select>
            <v-button
              class="mr-2"
              label="Set Pin State"
              on:click={setGPIO}
            />
            <v-input
              value={pwm}
              label="PWM Duty Cycle"
              type="number"
              class="mr-2"
              on:input={handlePwmInput}
            />
            <v-button
              class="mr-2"
              label="Set PWM Duty Cycle"
              on:click={setPWM}
            />
            <v-input
              value={pwmFrequency}
              label="PWM Frequency"
              type="number"
              class="mr-2"
              on:input={handlePwmFrequencyInput}
            />
            <v-button
              class="mr-2"
              label="Set PWM Frequency"
              on:click={setPWMFrequency}
            />
          </div>
        </td>
      </tr>
    </table>
  </div>
</Collapse>
