// web/frontend/src/components/camera/camera.svelte
<script lang="ts">

import { onMount, onDestroy } from 'svelte';
import { displayError } from '@/lib/error';
import {
  CameraClient,
  Client,
  type ResponseStream,
  robotApi,
  type ServiceError,
} from '@viamrobotics/sdk';
import { selectedMap } from '@/lib/camera-state';
import type { StreamManager } from './stream-manager';

export let cameraName: string;
export let client: Client;
export let showExportScreenshot: boolean;
export let refreshRate: string | undefined;
export let streamManager: StreamManager;
export let statusStream: ResponseStream<robotApi.StreamStatusResponse> | null;
export let triggerRefresh: boolean;

let imgEl: HTMLImageElement;
let videoEl: HTMLVideoElement;

let cameraFrameIntervalId = -1;
let isLive = false;

const cameraManager = streamManager.setCameraManager(cameraName);

const clearFrameInterval = () => {
  window.clearInterval(cameraFrameIntervalId);
};

const viewCameraFrame = (time: number) => {
  clearFrameInterval();
  cameraManager.setImageSrc(imgEl);
  if (time > 0) {
    cameraFrameIntervalId = window.setInterval(() => {
      cameraManager.setImageSrc(imgEl);
    }, Number(time) * 1000);
  }
};

const updateCameraRefreshRate = () => {
  if (refreshRate !== 'Live') {
    viewCameraFrame(selectedMap[refreshRate as keyof typeof selectedMap]);
  }
};

const exportScreenshot = async () => {
  let blob;
  try {
    blob = await new CameraClient(client, cameraName).renderFrame(
      'image/jpeg'
    );
  } catch (error) {
    displayError(error as ServiceError);
    return;
  }

  window.open(URL.createObjectURL(blob), '_blank');
};

onMount(() => {
  statusStream?.on('end', () => clearFrameInterval());

  videoEl.srcObject = cameraManager.videoStream;

  cameraManager.onOpen = () => {
    videoEl.srcObject = cameraManager.videoStream;
  };
});

onDestroy(() => {
  if (isLive) {
    cameraManager.removeStream();
  }

  cameraManager.onOpen = undefined;

  isLive = false;

  clearFrameInterval();
});

// on refreshRate change update camera and manage live connections
$: {
  if (isLive && refreshRate !== 'Live') {
    isLive = false;
    cameraManager.removeStream();
  }

  if (isLive === false && refreshRate === 'Live') {
    isLive = true;
    cameraManager.addStream();
  }

  updateCameraRefreshRate();
}

// on prop change refresh camera
$: updateCameraRefreshRate();

</script>

<div class="flex flex-col gap-2">
  {#if showExportScreenshot}
    <v-button
      class="mb-4"
      aria-label={`View camera: ${cameraName}`}
      icon="camera"
      label="Export screenshot"
      on:click={exportScreenshot}
    />
  {/if}

  <div class="max-w-screen-md">
    <video
      bind:this={videoEl}
      muted
      autoplay
      controls={false}
      playsinline
      aria-label={`${cameraName} stream`}
      class:hidden={refreshRate !== 'Live'}
      class="clear-both h-fit transition-all duration-300 ease-in-out"
    />

    <img
      alt='Camera stream'
      bind:this={imgEl}
      class:hidden={refreshRate === 'Live'}
      aria-label={`${cameraName} stream`}
    >
  </div>
</div>

// web/frontend/src/components/camera/camera.vue
<script setup lang="ts">
import { onMounted, onUnmounted, watch } from 'vue';
import { $ref } from 'vue/macros';
import { displayError } from '../../lib/error';
import {
  CameraClient,
  Client,
  commonApi,
  ServiceError,
} from '@viamrobotics/sdk';
import { selectedMap } from '../../lib/camera-state';
import type { CameraManager } from './camera-manager';
import type { StreamManager } from './stream-manager';

const props = defineProps< {
  cameraName: string;
  parentName: string;
  resources: commonApi.ResourceName.AsObject[];
  client: Client;
  showExportScreenshot: boolean;
  refreshRate: string | undefined;
  triggerRefresh: boolean;
  streamManager:StreamManager;
}>();

const imgEl = $ref<HTMLImageElement>();

let cameraOn = $ref(false);
let cameraFrameIntervalId = $ref(-1);
let isLive = false;
let cameraManager = $ref<CameraManager>();

const clearFrameInterval = () => {
  window.clearInterval(cameraFrameIntervalId);
};

const viewCameraFrame = (time: number) => {
  clearFrameInterval();
  cameraManager!.setImageSrc(imgEl);
  if (time > 0) {
    cameraFrameIntervalId = window.setInterval(() => {
      cameraManager!.setImageSrc(imgEl);
    }, Number(time) * 1000);
  }
};

const updateCameraRefreshRate = () => {
  if (props.refreshRate !== 'Live') {
    viewCameraFrame(selectedMap[props.refreshRate as keyof typeof selectedMap]);
  }
};

const setupManager = () => {
  let tempManager = props.streamManager.cameraManagers.get(props.cameraName);
  if (tempManager) {
    tempManager = props.streamManager.setCameraManager(props.cameraName);
  }
  cameraManager = tempManager;
};

const exportScreenshot = async (cameraName: string) => {
  let blob;
  try {
    blob = await new CameraClient(props.client, cameraName).renderFrame(
      'image/jpeg'
    );
  } catch (error) {
    displayError(error as ServiceError);
    return;
  }

  window.open(URL.createObjectURL(blob), '_blank');
};

const videoStream = $computed(() => {
  return cameraManager!.videoStream;
});

setupManager();

onMounted(() => {
  cameraOn = true;
  if (props.refreshRate === 'Live') {
    isLive = true;
    cameraManager!.addStream();
  }
  updateCameraRefreshRate();
});

onUnmounted(() => {
  if (isLive) {
    cameraManager!.removeStream();
  }
  cameraOn = false;
  isLive = false;
  clearFrameInterval();
});

// on refreshRate change update camera and manage live connections
watch(() => props.refreshRate, () => {
  if (isLive && props.refreshRate !== 'Live') {
    isLive = false;
    cameraManager!.removeStream();
  }
  if (isLive === false && props.refreshRate === 'Live') {
    isLive = true;
    cameraManager!.addStream();
  }
  updateCameraRefreshRate();
});

// on prop change refresh camera
watch(() => props.triggerRefresh, () => {
  updateCameraRefreshRate();
});

</script>

<template>
  <div class="flex flex-col gap-2">
    <template v-if="cameraOn">
      <v-button
        v-if="cameraOn && props.showExportScreenshot"
        :aria-label="`View Camera: ${cameraName}`"
        icon="camera"
        label="Export Screenshot"
        @click="exportScreenshot(cameraName)"
      />
    </template>

    <video
      v-show="props.refreshRate === 'Live'"
      :srcObject.prop="videoStream"
      muted
      autoplay
      controls="false"
      playsinline
      :aria-label="`${cameraName} stream`"
      :class="{ hidden: !cameraOn }"
      class="clear-both h-fit transition-all duration-300 ease-in-out"
    />

    <img
      v-show="props.refreshRate !== 'Live'"
      ref="imgEl"
      :aria-label="`${cameraName} stream`"
      :class="{ hidden: props.refreshRate === 'Live' }"
    >
  </div>
</template>
