// web/frontend/src/components/keyboard-input/index.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  export type Keys = "w" | "a" | "s" | "d";

  import {
    mdiArrowUp as w,
    mdiRestore as a,
    mdiReload as d,
    mdiArrowDown as s,
  } from "@mdi/js";
  import Icon from "../icon/index.svelte";

  export let isActive: boolean;
  export let onKeyDown: (key: Keys) => void;
  export let onKeyUp: (key: Keys) => void;
  export let onUpdateKeyboardState: (isActive: boolean) => void;

  const keyIcons = { w, a, s, d };

  const pressedKeys = {
    w: false,
    a: false,
    s: false,
    d: false,
  };

  const keysLayout = [["a"], ["w", "s"], ["d"]] as const;

  const normalizeKey = (key: string): Keys | null => {
    return (
      (
        {
          w: "w",
          a: "a",
          s: "s",
          d: "d",
          arrowup: "w",
          arrowleft: "a",
          arrowdown: "s",
          arrowright: "d",
        } as Record<string, Keys>
      )[key.toLowerCase()] ?? null
    );
  };

  const dispatchKeyDown = (key: Keys) => {
    pressedKeys[key] = true;
    onKeyDown(key);
  };

  const dispatchKeyUp = (key: Keys) => {
    pressedKeys[key] = false;
    onKeyUp(key);
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();

    const key = normalizeKey(event.key);

    if (key === null || pressedKeys[key]) {
      return;
    }

    dispatchKeyDown(key);
  };

  const handleKeyUp = (event: KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();

    const key = normalizeKey(event.key);
    if (key !== null) {
      dispatchKeyUp(key);
    }
  };

  const toggleKeyboard = (nowActive: boolean) => {
    if (nowActive) {
      window.addEventListener("keydown", handleKeyDown, false);
      window.addEventListener("keyup", handleKeyUp, false);
    } else {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    }

    onUpdateKeyboardState(nowActive);
  };

  const handlePointerDown = (key: Keys) => {
    dispatchKeyDown(key);
  };

  const handlePointerUp = (key: Keys) => {
    dispatchKeyUp(key);
  };

  $: if (!isActive) {
    toggleKeyboard(false);
  }

  onDestroy(() => {
    toggleKeyboard(false);
  });
</script>

<div>
  <v-switch
    label={isActive ? "Keyboard Enabled" : "Keyboard Disabled"}
    class="w-fit pr-4"
    value={isActive ? "on" : "off"}
    on:input={() => {
      toggleKeyboard(!isActive);
    }}
  />
  <div class="flex justify-center gap-2">
    {#each keysLayout as lineKeys, index (index)}
      <div class="my-1 flex flex-col gap-2 self-end">
        {#each lineKeys as key (key)}
          <button
            class="flex select-none items-center gap-1.5 border border-gray-500 px-3 py-1 uppercase outline-none"
            class:bg-gray-200={pressedKeys[key]}
            class:text-gray-800={pressedKeys[key]}
            class:bg-white={!pressedKeys[key]}
            on:pointerdown={() => {
              handlePointerDown(key);
            }}
            on:pointerup={() => {
              handlePointerUp(key);
            }}
            on:pointerleave={() => {
              handlePointerUp(key);
            }}
          >
            {key}
            <Icon path={keyIcons[key]} />
          </button>
        {/each}
      </div>
    {/each}
  </div>
</div>

// web/frontend/dls/src/components/KeyboardInput.vue
<template>
  <div
    class="flex flex-col h-23"
  >
    <div class="flex pb-4">
      <div class="pr-4 w-16">
        <!-- <ViamBadge v-if="isActive" color="green">On</ViamBadge>
        <ViamBadge v-if="!isActive" color="gray">Off</ViamBadge> -->
        <ViamSwitch
        class="pr-4"
        centered
        :option="isActive"
        @change="toggleKeyboard()"
      ></ViamSwitch>
      </div>
      <h3 v-if="isActive">Keyboard active</h3>
      <h3 v-else>Keyboard disabled</h3>
    </div>
    <div
      v-for="(lineKeys, index) in keysLayout"
      :key="index"
      class="flex flex-row justify-center"
    >
      <ViamButton
        v-for="key in lineKeys"
        :key="key"
        color="primary"
        group
        variant="primary"
        @pointerdown="setKeyPressed(key, true)"
        @pointerup="setKeyPressed(key, false)"
        class="w-15 h-10 m-1 bg-white dark:bg-gray-900 border-gray-500"
        :class="{
          'bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 keyboard-button-pressed':
            pressedKeys[key],
          'keyboard-button-not-pressed': !pressedKeys[key],
        }"
      >
        <template v-slot:icon>
          <ViamIcon :path="keyIcons[key]">Check</ViamIcon>
        </template>
        <span class="text-2xl">{{ keyLetters[key] }}</span>
      </ViamButton>
    </div>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { throttle, debounce } from "lodash";
import { mdiRestore, mdiReload, mdiArrowUp, mdiArrowDown } from "@mdi/js";
import ViamIcon from "./ViamIcon.vue";
import ViamButton from "./Button.vue";
import ViamSwitch from "./Switch.vue";
import Badge from "./Badge.vue";

const PressedKeysMap: { [index: string]: string } = {
  "87": "forward",
  "83": "backward",
  "65": "left",
  "68": "right",
};

// TODO: remove debounce if not needed
const inputDelay = 0;
const eventsDelay = 0;

@Component({
  components: {
    ViamIcon,
    ViamButton,
    ViamSwitch,
    Badge,
  },
})
export default class KeyboardInput extends Vue {
  pressedKeys: { [index: string]: boolean } = {
    forward: false,
    left: false,
    backward: false,
    right: false,
  };

  mdiRestore = mdiRestore;
  mdiReload = mdiReload;
  mdiArrowUp = mdiArrowUp;
  mdiArrowDown = mdiArrowDown;
  isActive = false;

  keyLetters = {
    forward: "W",
    left: "A",
    backward: "S",
    right: "D",
  };

  keyIcons = {
    forward: mdiArrowUp,
    left: mdiRestore,
    backward: mdiArrowDown,
    right: mdiReload,
  };

  //for template section
  keysLayout = [["forward"], ["left", "backward", "right"]];

  sendKeysState = debounce(() => {
    this.handleKeysStateInstantly();
  }, inputDelay);

  handleKeysStateInstantly(): void {
    this.emitEvent("keyboard-ctl");
  }

  emitEvent = throttle((eventName: string) => {
    this.emitEventInstantly(eventName);
  }, eventsDelay);

  emitEventInstantly(eventName: string): void {
    this.$emit(eventName, this.pressedKeys);
  }
  setKeyPressed(key: string, value = true): void {
    this.pressedKeys[key] = value;
    this.sendKeysState();
  }

  onUseKeyboardNav(event: KeyboardEvent): void {
    const key = PressedKeysMap[event.keyCode];
    if (!key) return;
    this.setKeyPressed(key, event.type === "keydown");
    event.preventDefault();
  }

  toggleKeyboard(): void {
    if (this.isActive === true) {
      this.removeKeyboardListeners();
    } else {
      this.addKeyboardListeners();
    }
  }

  addKeyboardListeners(): void {
    this.isActive = true;
    window.addEventListener("keydown", this.onUseKeyboardNav, false);
    window.addEventListener("keyup", this.onUseKeyboardNav, false);
  }

  removeKeyboardListeners(): void {
    this.isActive = false;
    window.removeEventListener("keydown", this.onUseKeyboardNav);
    window.removeEventListener("keyup", this.onUseKeyboardNav);
  }
}
</script>
<style>
.keyboard-button-not-pressed:focus {
  background-color: white;
}
.keyboard-button-pressed:focus {
  background-color: rgba(228, 228, 231, 1);
}
</style>
