// web/frontend/src/components/audio-input/index.svelte
<script lang='ts'>

import { StreamClient } from '@viamrobotics/sdk';
import type { Client, ServiceError } from '@viamrobotics/sdk';
import { displayError } from '@/lib/error';

export let name: string;
export let client: Client;

let isOn = false;

const toggleExpand = async () => {
  isOn = !isOn

  const streams = new StreamClient(client);

  if (isOn) {
    try {
      await streams.add(name);
    } catch (error) {
      displayError(error as ServiceError);
    }
    return;
  }

  try {
    await streams.remove(name);
  } catch (error) {
    displayError(error as ServiceError);
  }
};

</script>

<v-collapse title={name}>
  <v-breadcrumbs slot="title" crumbs="audio_input" />
  <div class="h-auto border border-t-0 border-medium p-2">
    <div class="container mx-auto">
      <div class="pt-4">
        <div class="flex items-center gap-2">
          <v-switch
            id="audio-input"
            value={isOn ? 'on' : 'off'}
            on:change={toggleExpand}
          />
          <span class="pr-2">Listen</span>
        </div>

        {#if isOn}
          <div
            data-stream={name}
            class="clear-both h-fit transition-all duration-300 ease-in-out"
          />
        {/if}
      </div>
    </div>
  </div>
</v-collapse>

// web/frontend/src/components/audio-input.vue
<script setup lang="ts">

import { ref } from 'vue';
import { StreamClient } from '@viamrobotics/sdk';
import type { Client, ServiceError } from '@viamrobotics/sdk';
import { displayError } from '../lib/error';

const props = defineProps<{
  name: string
  client: Client
}>();

const audioInput = ref(false);

const toggleExpand = async () => {
  audioInput.value = !audioInput.value;

  const isOn = audioInput.value;

  const streams = new StreamClient(props.client);
  if (isOn) {
    try {
      await streams.add(props.name);
    } catch (error) {
      displayError(error as ServiceError);
    }
    return;
  }

  try {
    await streams.remove(props.name);
  } catch (error) {
    displayError(error as ServiceError);
  }
};

</script>

<template>
  <v-collapse :title="name">
    <v-breadcrumbs
      slot="title"
      crumbs="audio_input"
    />
    <div class="border-medium h-auto border-x border-b p-2">
      <div class="container mx-auto">
        <div class="pt-4">
          <div class="flex items-center gap-2">
            <v-switch
              id="audio-input"
              :value="audioInput ? 'on' : 'off'"
              @input="toggleExpand"
            />
            <span class="pr-2">Listen</span>
          </div>

          <div
            v-if="audioInput"
            :data-stream="props.name"
            class="clear-both h-fit transition-all duration-300 ease-in-out"
          />
        </div>
      </div>
    </div>
  </v-collapse>
</template>
