// web/frontend/src/components/camera/index.svelte
<script lang="ts">
import type {
  commonApi,
  Client,
  ResponseStream,
  robotApi,
} from '@viamrobotics/sdk';

import Camera from './camera.svelte';
import PCD from '../pcd/index.svelte';
import Collapse from '../collapse.svelte';
import { selectedMap } from '@/lib/camera-state';
import type { StreamManager } from './stream-manager';

export let resources: commonApi.ResourceName.AsObject[];
export let streamManager: StreamManager;
export let client: Client;
export let statusStream: ResponseStream<robotApi.StreamStatusResponse> | null;

const openCameras: Record<string, boolean | undefined> = {};
const refreshFrequency: Record<string, string | undefined> = {};

let triggerRefresh = false;

const setupCamera = (cameraName: string) => {
  openCameras[cameraName] = !openCameras[cameraName];

  for (const camera of resources) {
    if (!refreshFrequency[camera.name]) {
      refreshFrequency[camera.name] = 'Live';
    }
  }
};

const handleRefreshInput = (name: string) => {
  return (event: CustomEvent) => {
    refreshFrequency[name] = event.detail.value;
  };
};

</script>

{#each resources as camera (camera.name)}
  <Collapse title={camera.name}>
    <v-breadcrumbs
      slot="title"
      crumbs="camera"
    />

    <div class="flex flex-col gap-4 border border-t-0 border-medium p-4">
      <v-switch
        label={`View ${camera.name}`}
        aria-label={openCameras[camera.name] ? `Hide Camera: ${camera.name}` : `View Camera: ${camera.name}`}
        value={openCameras[camera.name] ? 'on' : 'off'}
        on:input={() => setupCamera(camera.name)}
      />

      {#if openCameras[camera.name]}
        <div class="flex flex-wrap items-end gap-2">
          <v-select
            value={refreshFrequency[camera.name]}
            class="w-fit"
            label="Refresh frequency"
            aria-label="Refresh frequency"
            options={Object.keys(selectedMap).join(',')}
            on:input={handleRefreshInput(camera.name)}
          />

          {#if refreshFrequency[camera.name] !== 'Live'}
            <v-button
              icon="refresh"
              label="Refresh"
              on:click={() => {
                triggerRefresh = !triggerRefresh;
              }}
            />
          {/if}
        </div>
      {/if}

      {#if openCameras[camera.name]}
        <Camera
          {client}
          {streamManager}
          {statusStream}
          cameraName={camera.name}
          showExportScreenshot={true}
          refreshRate={refreshFrequency[camera.name]}
        />
      {/if}

      <PCD
        {client}
        cameraName={camera.name}
      />
    </div>
  </Collapse>
{/each}

// web/frontend/src/components/camera.vue
<script setup lang="ts">

import { ref, onMounted } from 'vue';
import { displayError } from '../lib/error';
import { StreamClient, CameraClient, Camera, Client, commonApi, ServiceError } from '@viamrobotics/sdk';
import { toast } from '../lib/toast';
import InfoButton from './info-button.vue';
import PCD from './pcd.vue';
import { cameraStreamStates, baseStreamStates } from '../lib/camera-state';

interface Props {
  cameraName: string
  resources: commonApi.ResourceName.AsObject[];
  client: Client;
}

interface Emits {
  (event: 'download-raw-data'): void
  (event: 'clear-interval'): void
  (event: 'selected-camera-view', value: string): void
  (event: 'refresh-camera', value: string): void
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

let pcdExpanded = $ref(false);
let pointcloud = $ref<Uint8Array | undefined>();
let camera = $ref(false);

const selectedValue = ref('live');

const initStreamState = () => {
  cameraStreamStates.set(props.cameraName, false);
};

const viewCamera = async (isOn: boolean) => {
  const streams = new StreamClient(props.client);
  if (isOn) {
    try {
      // only add stream if not already active
      if (!baseStreamStates.get(props.cameraName) && !cameraStreamStates.get(props.cameraName)) {
        await streams.add(props.cameraName);
      }
    } catch (error) {
      displayError(error as ServiceError);
    }
    cameraStreamStates.set(props.cameraName, true);
  } else {
    try {
      // only remove camera stream if active and base stream is not active
      if (!baseStreamStates.get(props.cameraName) && cameraStreamStates.get(props.cameraName)) {
        await streams.remove(props.cameraName);
      }
    } catch (error) {
      displayError(error as ServiceError);
    }
    cameraStreamStates.set(props.cameraName, false);
  }
};

const toggleExpand = () => {
  camera = !camera;
  viewCamera(camera);
};

const renderPCD = async () => {
  try {
    pointcloud = await new CameraClient(props.client, props.cameraName).getPointCloud();
  } catch (error) {
    toast.error(`Error getting point cloud: ${error}`);
  }
};

const togglePCDExpand = () => {
  pcdExpanded = !pcdExpanded;
  if (pcdExpanded) {
    renderPCD();
  }
};

const selectCameraView = () => {
  if (selectedValue.value !== 'live') {
    viewCamera(false);
    emit('selected-camera-view', selectedValue.value);
    return;
  }

  emit('clear-interval');
  viewCamera(true);
};

const refreshCamera = () => {
  emit('selected-camera-view', selectedValue.value);
  emit('clear-interval');
};

const exportScreenshot = async (cameraName: string) => {
  let blob;
  try {
    blob = await new CameraClient(props.client, cameraName).renderFrame(Camera.MimeType.JPEG);
  } catch (error) {
    displayError(error as ServiceError);
    return;
  }

  window.open(URL.createObjectURL(blob), '_blank');
};

onMounted(() => {
  initStreamState();
});
</script>

<template>
  <v-collapse
    :title="cameraName"
    class="camera"
  >
    <v-breadcrumbs
      slot="title"
      crumbs="camera"
    />
    <div class="h-auto border-x border-b border-black p-2">
      <div class="container mx-auto">
        <div class="pt-4">
          <div class="flex mb-4 items-center gap-2">
            <v-switch
              id="camera"
              :label="camera ? 'Hide Camera' : 'View Camera'"
              :aria-label="camera ? `Hide Camera: ${$props.cameraName}` : `View Camera: ${$props.cameraName}`"
              :value="camera ? 'on' : 'off'"
              @input="toggleExpand"
            />
          </div>

          <div class="pb-4">
            <div class="flex flex-wrap">
              <div
                v-if="camera"
                class="flex flex-wrap justify-items-end gap-2"
              >
                <div class="">
                  <div class="relative">
                    <v-select
                      v-model="selectedValue"
                      label="Refresh frequency"
                      aria-label="Default select example"
                      options="Manual Refresh, Every 30 Seconds, Every 10 Seconds, Every Second, Live"
                      @input="selectCameraView"
                    />
                  </div>
                </div>
                <div class="self-end">
                  <v-button
                    v-if="(camera && selectedValue === 'Manual Refresh')"
                    icon="refresh"
                    label="Refresh"
                    @click="refreshCamera"
                  />
                </div>
                <div class="self-end">
                  <v-button
                    v-if="camera"
                    icon="camera"
                    label="Export Screenshot"
                    @click="exportScreenshot(cameraName)"
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            :aria-label="`${cameraName} stream`"
            :data-stream="cameraName"
            :class="{ 'hidden': !camera }"
            class="clear-both h-fit transition-all duration-300 ease-in-out"
          />
        </div>
        <div class="pt-4">
          <div class="flex items-center gap-2 align-top">
            <v-switch
              :label="pcdExpanded ? 'Hide Point Cloud Data' : 'View Point Cloud Data'"
              :value="pcdExpanded ? 'on' : 'off'"
              @input="togglePCDExpand"
            />
            <InfoButton :info-rows="['When turned on, point cloud will be recalculated']" />
          </div>

          <PCD
            v-if="pcdExpanded"
            :resources="resources"
            :pointcloud="pointcloud"
            :camera-name="cameraName"
            :client="client"
          />
        </div>
      </div>
    </div>
  </v-collapse>
</template>
