// web/frontend/src/components/encoder/index.svelte
<script lang="ts">

import { onMount, onDestroy } from 'svelte';
import { type Client, encoderApi, type ResponseStream, robotApi, type ServiceError } from '@viamrobotics/sdk';
import { displayError } from '@/lib/error';
import { setAsyncInterval } from '@/lib/schedule';
import { getProperties, getPosition, getPositionDegrees, reset } from '@/api/encoder';
import Collapse from '@/components/collapse.svelte';

export let name: string;
export let client: Client;
export let statusStream: ResponseStream<robotApi.StreamStatusResponse> | null;

let properties: encoderApi.GetPropertiesResponse.AsObject | undefined;
let positionTicks: number | undefined;
let positionDegrees: number | undefined;

let cancelInterval: (() => void) | undefined;

const refresh = async () => {
  try {
    const results = await Promise.all([
      getPosition(client, name),
      properties?.angleDegreesSupported ? getPositionDegrees(client, name) : undefined,
    ] as const);

    positionTicks = results[0];
    positionDegrees = results[1];
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const handleResetClick = async () => {
  try {
    await reset(client, name);
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const handleToggle = async (event: CustomEvent<{ open: boolean }>) => {
  if (event.detail.open) {
    try {
      properties = await getProperties(client, name);
      refresh();
      cancelInterval = setAsyncInterval(refresh, 500);
    } catch (error) {
      displayError(error as ServiceError);
    }
  } else {
    cancelInterval?.();
  }
};

onMount(() => {
  statusStream?.on('end', () => cancelInterval?.());
});

onDestroy(() => {
  cancelInterval?.();
});

</script>

<Collapse title={name} on:toggle={handleToggle}>
  <v-breadcrumbs
    slot="title"
    crumbs="encoder"
  />
  <div class="overflow-auto border border-t-0 border-medium p-4 text-left text-sm">
    <table class="bborder-medium table-auto border">
      {#if properties?.ticksCountSupported || (!properties?.ticksCountSupported && !properties?.angleDegreesSupported)}
        <tr>
          <th class="border border-medium p-2">
            Count
          </th>
          <td class="border border-medium p-2">
            {positionTicks?.toFixed(2)}
          </td>
        </tr>
      {/if}

      {#if (
        properties?.angleDegreesSupported ||
        (!properties?.ticksCountSupported && !properties?.angleDegreesSupported)
      )}
        <tr>
          <th class="border border-medium p-2">
            Angle (degrees)
          </th>
          <td class="border border-medium p-2">
            {positionDegrees?.toFixed(2)}
          </td>
        </tr>
      {/if}
    </table>

    <div class="mt-2 flex gap-2">
      <v-button
        label="Reset"
        class="flex-auto"
        on:click={handleResetClick}
      />
    </div>
  </div>
</Collapse>

// web/frontend/src/components/encoder.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { $ref } from '@vue-macros/reactivity-transform/macros';
import { grpc } from '@improbable-eng/grpc-web';
import { Client, encoderApi, type ResponseStream, robotApi, type ServiceError } from '@viamrobotics/sdk';
import { displayError } from '../lib/error';
import { rcLogConditionally } from '../lib/log';
import { setAsyncInterval } from '../lib/schedule';

const props = defineProps<{
  name: string
  client: Client
  statusStream: ResponseStream<robotApi.StreamStatusResponse> | null
}>();

let properties = $ref<encoderApi.GetPropertiesResponse.AsObject>();
let positionTicks = $ref(0);
let positionDegrees = $ref(0);

let cancelInterval: (() => void) | undefined;

const getProperties = () => new Promise<encoderApi.GetPropertiesResponse.AsObject>((resolve, reject) => {
  const request = new encoderApi.GetPropertiesRequest();
  request.setName(props.name);

  rcLogConditionally(request);
  props.client.encoderService.getProperties(request, new grpc.Metadata(), (error, response) => {
    if (error) {
      return reject((error as ServiceError).message);
    }

    resolve(response!.toObject());
  });
});

const getPosition = () => new Promise<number>((resolve, reject) => {
  const request = new encoderApi.GetPositionRequest();
  request.setName(props.name);
  rcLogConditionally(request);
  props.client.encoderService.getPosition(request, new grpc.Metadata(), (error, resp) => {
    if (error) {
      return reject(new Error((error as ServiceError).message));
    }

    resolve(resp!.toObject().value);
  });
});

const getPositionDegrees = () => new Promise<number>((resolve, reject) => {
  const request = new encoderApi.GetPositionRequest();
  request.setPositionType(2);
  rcLogConditionally(request);

  props.client.encoderService.getPosition(request, new grpc.Metadata(), (error, resp) => {
    if (error) {
      return reject(new Error((error as ServiceError).message));
    }

    resolve(resp!.toObject().value);
  });
});

const refresh = async () => {
  try {
    positionTicks = await getPosition();

    if (properties?.angleDegreesSupported) {
      positionDegrees = await getPositionDegrees();
    }
  } catch (error) {
    displayError(error as ServiceError);
  }
};

const reset = () => {
  const request = new encoderApi.ResetPositionRequest();
  request.setName(props.name);

  rcLogConditionally(request);

  props.client.encoderService.resetPosition(request, new grpc.Metadata(), (error) => {
    if (error) {
      return displayError(error as ServiceError);
    }
  });
};

onMounted(async () => {
  try {
    properties = await getProperties();
    refresh();
    cancelInterval = setAsyncInterval(refresh, 500);
  } catch (error) {
    displayError(error as ServiceError);
  }

  props.statusStream?.on('end', () => cancelInterval?.());
});

onUnmounted(() => {
  cancelInterval?.();
});

</script>

<template>
  <v-collapse
    :title="name"
    class="encoder"
  >
    <v-breadcrumbs
      slot="title"
      crumbs="encoder"
    />
    <div class="border-medium overflow-auto border border-t-0 p-4 text-left">
      <table class="bborder-medium table-auto border">
        <tr
          v-if="properties && (properties.ticksCountSupported ||
            (!properties.ticksCountSupported && !properties.angleDegreesSupported))"
        >
          <th class="border-medium border p-2">
            Count
          </th>
          <td class="border-medium border p-2">
            {{ positionTicks.toFixed(2) || 0 }}
          </td>
        </tr>
        <tr
          v-if="properties && (properties.angleDegreesSupported ||
            (!properties.ticksCountSupported && !properties.angleDegreesSupported))"
        >
          <th class="border-medium border p-2">
            Angle (degrees)
          </th>
          <td class="border-medium border p-2">
            {{ positionDegrees.toFixed(2) || 0 }}
          </td>
        </tr>
      </table>
      <div class="mt-2 flex gap-2">
        <v-button
          label="Reset"
          class="flex-auto"
          @click="reset"
        />
      </div>
    </div>
  </v-collapse>
</template>
