// web/frontend/src/components/keyboard-input/index.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  export type Keys = "w" | "a" | "s" | "d";

  import {
    mdiArrowUp as w,
    mdiRestore as a,
    mdiReload as d,
    mdiArrowDown as s,
  } from "@mdi/js";
  import Icon from "../icon/index.svelte";

  export let isActive: boolean;
  export let onKeyDown: (key: Keys) => void;
  export let onKeyUp: (key: Keys) => void;
  export let onUpdateKeyboardState: (isActive: boolean) => void;

  const keyIcons = { w, a, s, d };

  const pressedKeys = {
    w: false,
    a: false,
    s: false,
    d: false,
  };

  const keysLayout = [["a"], ["w", "s"], ["d"]] as const;

  const normalizeKey = (key: string): Keys | null => {
    return (
      (
        {
          w: "w",
          a: "a",
          s: "s",
          d: "d",
          arrowup: "w",
          arrowleft: "a",
          arrowdown: "s",
          arrowright: "d",
        } as Record<string, Keys>
      )[key.toLowerCase()] ?? null
    );
  };

  const dispatchKeyDown = (key: Keys) => {
    pressedKeys[key] = true;
    onKeyDown(key);
  };

  const dispatchKeyUp = (key: Keys) => {
    pressedKeys[key] = false;
    onKeyUp(key);
  };

  const handleKeyDown = (event: KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();

    const key = normalizeKey(event.key);

    if (key === null || pressedKeys[key]) {
      return;
    }

    dispatchKeyDown(key);
  };

  const handleKeyUp = (event: KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();

    const key = normalizeKey(event.key);
    if (key !== null) {
      dispatchKeyUp(key);
    }
  };

  const toggleKeyboard = (nowActive: boolean) => {
    if (nowActive) {
      window.addEventListener("keydown", handleKeyDown, false);
      window.addEventListener("keyup", handleKeyUp, false);
    } else {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    }

    onUpdateKeyboardState(nowActive);
  };

  const handlePointerDown = (key: Keys) => {
    dispatchKeyDown(key);
  };

  const handlePointerUp = (key: Keys) => {
    dispatchKeyUp(key);
  };

  $: if (!isActive) {
    toggleKeyboard(false);
  }

  onDestroy(() => {
    toggleKeyboard(false);
  });
</script>

<div>
  <v-switch
    label={isActive ? "Keyboard Enabled" : "Keyboard Disabled"}
    class="w-fit pr-4"
    value={isActive ? "on" : "off"}
    on:input={() => {
      toggleKeyboard(!isActive);
    }}
  />
  <div class="flex justify-center gap-2">
    {#each keysLayout as lineKeys, index (index)}
      <div class="my-1 flex flex-col gap-2 self-end">
        {#each lineKeys as key (key)}
          <button
            class="flex select-none items-center gap-1.5 border border-gray-500 px-3 py-1 uppercase outline-none"
            class:bg-gray-200={pressedKeys[key]}
            class:text-gray-800={pressedKeys[key]}
            class:bg-white={!pressedKeys[key]}
            on:pointerdown={() => {
              handlePointerDown(key);
            }}
            on:pointerup={() => {
              handlePointerUp(key);
            }}
            on:pointerleave={() => {
              handlePointerUp(key);
            }}
          >
            {key}
            <Icon path={keyIcons[key]} />
          </button>
        {/each}
      </div>
    {/each}
  </div>
</div>

// web/frontend/src/components/KeyboardInput.vue
<script setup lang="ts">

import { ref } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { mdiRestore, mdiReload, mdiArrowUp, mdiArrowDown } from '@mdi/js';
import Icon from './icon.vue';

interface Emits {
  (event: 'keyboard-ctl', pressedKeys: Record<string, boolean>): void
}

const emit = defineEmits<Emits>();

const pressedKeysMap = {
  w: 'forward',
  s: 'backward',
  a: 'left',
  d: 'right',
} as const;

const pressedKeys = ref({
  forward: false,
  left: false,
  backward: false,
  right: false,
});

const root = ref();
const isActive = ref(false);

const keyLetters = {
  forward: 'W',
  left: 'A',
  backward: 'S',
  right: 'D',
};

const keyIcons = {
  forward: mdiArrowUp,
  left: mdiRestore,
  backward: mdiArrowDown,
  right: mdiReload,
};

const keysLayout = [['forward'], ['left', 'backward', 'right']] as const;

const setKeyPressed = (key: keyof typeof pressedKeys.value, value = true) => {
  pressedKeys.value[key] = value;
  emit('keyboard-ctl', pressedKeys.value);
};

const onUseKeyboardNav = (event: KeyboardEvent) => {
  const key = pressedKeysMap[event.key as 'w' | 's' | 'a' | 'd'];

  if (!key) {
    return; 
  }

  setKeyPressed(key, event.type === 'keydown');
  event.preventDefault();
};

const toggleKeyboard = () => {
  if (isActive.value) {
    removeKeyboardListeners();
  } else {
    addKeyboardListeners();
  }
};

const addKeyboardListeners = () => {
  isActive.value = true;
  window.addEventListener('keydown', onUseKeyboardNav, false);
  window.addEventListener('keyup', onUseKeyboardNav, false);
};

const removeKeyboardListeners = () => {
  isActive.value = false;
  window.removeEventListener('keydown', onUseKeyboardNav);
  window.removeEventListener('keyup', onUseKeyboardNav);
};

onClickOutside(root, () => {
  removeKeyboardListeners();
});

</script>

<template>
  <div
    ref="root"
    class="h-23 flex flex-col"
  >
    <div class="flex pb-4">
      <v-switch
        class="pr-4"
        :value="isActive ? 'on' : 'off'"
        @input="toggleKeyboard()"
      />
      <h3 v-if="isActive">
        Keyboard active
      </h3>
      <h3 v-else>
        Keyboard disabled
      </h3>
    </div>
    <div
      v-for="(lineKeys, index) in keysLayout"
      :key="index"
      class="my-1 flex flex-row justify-center gap-2"
    >
      <v-button
        v-for="key in lineKeys"
        :key="key"
        icon="check"
        :label="keyLetters[key]"
        class="border-gray-500 bg-white dark:bg-gray-900"
        :class="{
          'bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 keyboard-button-pressed': pressedKeys[key],
          'keyboard-button-not-pressed': !pressedKeys[key],
        }"
        @pointerdown="setKeyPressed(key, true)"
        @pointerup="setKeyPressed(key, false)"
      >
        <Icon :path="keyIcons[key]">
          Check
        </Icon>
      </v-button>
    </div>
  </div>
</template>

<style>

.keyboard-button-not-pressed:focus {
  background-color: white;
}
.keyboard-button-pressed:focus {
  background-color: rgba(228, 228, 231, 1);
}

</style>
